@isTest
public class SendExpirationEmailToBPTest
{
    
    static testMethod void unitTest(){
        /*
        Vendor__c objVendor = new Vendor__c();
        objVendor.Name = 'Test';
        objVendor.Email__c = 'test@test.com';
        insert objVendor     
        Trade_Licensing__c objTradeLicensing = new Trade_Licensing__c();
        objTradeLicensing.Name = 'test';
        objTradeLicensing.Vendor__c = objVendor.Id;
        objTradeLicensing.Expiration_Date__c = Date.today();
        insert objTradeLicensing     
        new SendExpirationEmailToBP().execute(null);
        */
        SendExpirationEmailToBP test = new SendExpirationEmailToBP();


    }
}